# emulator runs tests inside the android emulator
name: emulator
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 2 * * */2"
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [google_apis]
    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: checkout
      uses: actions/checkout@v2
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        ram-size: 4096M
        cores: 4
        script: ./gradlew connectedStableFullDebugAndroidTest
    - name: uploads test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: emulator-test-results
        path: app/build/reports/androidTests/connected/flavors/stableFullDebugAndroidTest
